### ISSUE TITLE
Docmentation says to require ldap-client

### ISSUE THREAD

**Issue by cout** [jjhoughton/napi-ldap#9]
`README.md` says that to use napi-ldap, I should require ldap-client:

```
var LDAP = require('ldap-client');
```

Should this say napi-ldap instead?

**Comment by jjhoughton** [comment]
Sorry that's a really good point. It's a rewrite of this project https://github.com/jeremycx/node-LDAP I guess i forgot to update the documentation, I will do so shortly when i've finished work. You are correct it should be `const LDAP = require("napi-ldap");`

**Comment by jjhoughton** [comment]
Thanks for raising it.

**Comment by jjhoughton** [comment]
Closing as the documentation has been updated in v1.0.2.
